FORMAT: 1A

# customer-journey

Simple API to manage customer journey data dependencies.

## Hi Collection [/hi]


### Get a salute [GET]

+ Response 201 (application/json)

    + Headers

            Location: /questions/3

    + Body
            {
                responde: "Hi!"
            }


## Quote Collection [/quote]


### Get a fake quote [GET]

Get a fake quote for free!!


+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

    {
        "activityid": "4615",
        "ref_dossier": "2bc21f28bf388bbf6d20d3f26419cab9",
        "octo_control_group": "2015_harvest9_a",
        "quotingRequests": [
            {
                "insurance_id": "c911",
                "insurance_data": {
                    "insurance_name": "ConTe",
                    "insurance_teaser": "",
                    "insurance_logo": "",
                    "saving_allowed": 1,
                    "autosaving": 1,
                    "expiration": 0,
                    "full_price": 313.91,
                    "bundle_covers": [1]
                    "commission_abs": 55,
                    "commission_rel": 17.52
                },
                "enrichments": [{
                    "enrichment_name": "autosaving",
                    "enrichment_value": "1st Quote - autosave"
                }]
            },
            {
                "insurance_id": 440,
                "insurance_data": {
                    "insurance_name": "Quixa",
                    "insurance_teaser": "",
                    "insurance_logo": "",
                    "saving_allowed": 1,
                    "autosaving": 0,
                    "expiration": 0,
                    "full_price": "764",
                    "bundle_covers": [1],
                    "enrichments": [],
                    "commission_abs": 16,
                    "commission_rel": 2.09,
                    "covers": [
                        {
                          "cover_id": 5,
                          "cover_value": "40"
                        }, 
                        {
                          "cover_id": 7,
                          "cover_value": "19"
                        }, 
                        {
                          "cover_id": 9,
                          "cover_value": "24"
                        }
                    ]
                }
            }
        ]
    }