FORMAT: 1A

# customer-journey

Simple API to manage customer journey data dependencies.

## Hi Collection [/hi]


### Get a salute [GET]

+ Response 201 (application/json)

    + Headers

            Location: /questions/3

    + Body
            {
                responde: "Hi!"
            }


## Quote Collection [/quote]


### Get a fake quote [GET]

Get a fake quote for free!!


+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

    {
      "ref_dossier": "2bc21f28bf388bbf6d20d3f26419cab9",
      "octo_control_group": "2015_harvest9_a",
      "data": {
        "activityid": "4615",
        "ref_dossier": "2bc21f28bf388bbf6d20d3f26419cab9",
        "octo_control_group": "2015_harvest9_a",
        "quotingRequests": {
          "quotingRequest": [{
            "insurance_id": "c911",
            "insurance_data": {
              "insurance_name": "ConTe",
              "insurance_teaser": "",
              "insurance_logo": "",
              "saving_allowed": 1,
              "autosaving": 1,
              "expiration": 0,
              "full_price": 313.91,
              "bundle_covers": {
                "bundle_cover": [1]
              },
              "enrichments": {
                "enrichment": [{
                  "enrichment_name": "autosaving",
                  "enrichment_value": "1st Quote - autosave"
                }]
              },
              "commission_abs": 55,
              "commission_rel": 17.52,
              "covers": {
                "cover": []
              },
              "pack_covers": {
                "pack_cover": [{
                  "pack_cover_id": "conte_1",
                  "pack_cover_value": 313.91,
                  "pack_cover_list": {
                    "pack_cover_cover": [1]
                  }
                }, {
                  "pack_cover_id": "conte_1_3",
                  "pack_cover_value": 397.68,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3"]
                  }
                }, {
                  "pack_cover_id": "conte_1_11",
                  "pack_cover_value": 514.72,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_11",
                  "pack_cover_value": 598.49,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_10",
                  "pack_cover_value": 469.53,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_10_11",
                  "pack_cover_value": 670.34,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_8",
                  "pack_cover_value": 357.49,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "8"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_8",
                  "pack_cover_value": 441.26,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "8"]
                  }
                }, {
                  "pack_cover_id": "conte_1_8_11",
                  "pack_cover_value": 558.3,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "8", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_8_11",
                  "pack_cover_value": 642.07,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "8", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_8_10",
                  "pack_cover_value": 513.11,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "8", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_8_10_11",
                  "pack_cover_value": 713.92,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "8", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_7",
                  "pack_cover_value": 333.81,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "7"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7",
                  "pack_cover_value": 417.58,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7"]
                  }
                }, {
                  "pack_cover_id": "conte_1_7_11",
                  "pack_cover_value": 534.62,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "7", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_11",
                  "pack_cover_value": 618.39,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_10",
                  "pack_cover_value": 489.43,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_10_11",
                  "pack_cover_value": 690.24,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_7_8",
                  "pack_cover_value": 377.39,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "7", "8"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_8",
                  "pack_cover_value": 461.16,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "8"]
                  }
                }, {
                  "pack_cover_id": "conte_1_7_8_11",
                  "pack_cover_value": 578.2,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "7", "8", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_8_11",
                  "pack_cover_value": 661.97,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "8", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_8_10",
                  "pack_cover_value": 533.01,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "8", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_8_10_11",
                  "pack_cover_value": 733.82,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "8", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_9",
                  "pack_cover_value": 332.91,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_9",
                  "pack_cover_value": 416.68,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_9_11",
                  "pack_cover_value": 533.72,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_9_11",
                  "pack_cover_value": 617.49,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_9_10",
                  "pack_cover_value": 488.53,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "9", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_9_10_11",
                  "pack_cover_value": 689.34,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "9", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_8_9",
                  "pack_cover_value": 376.49,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "8", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_8_9",
                  "pack_cover_value": 460.26,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "8", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_8_9_11",
                  "pack_cover_value": 577.3,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "8", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_8_9_11",
                  "pack_cover_value": 661.07,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "8", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_8_9_10",
                  "pack_cover_value": 532.11,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "8", "9", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_8_9_10_11",
                  "pack_cover_value": 732.92,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "8", "9", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_7_9",
                  "pack_cover_value": 352.81,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "7", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_9",
                  "pack_cover_value": 436.58,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_7_9_11",
                  "pack_cover_value": 553.62,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "7", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_9_11",
                  "pack_cover_value": 637.39,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_9_10",
                  "pack_cover_value": 508.43,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "9", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_9_10_11",
                  "pack_cover_value": 709.24,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "9", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_7_8_9",
                  "pack_cover_value": 396.39,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "7", "8", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_8_9",
                  "pack_cover_value": 480.16,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "8", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_7_8_9_11",
                  "pack_cover_value": 597.2,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "7", "8", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_8_9_11",
                  "pack_cover_value": 680.97,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "8", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_8_9_10",
                  "pack_cover_value": 552.01,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "8", "9", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_7_8_9_10_11",
                  "pack_cover_value": 752.82,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "7", "8", "9", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5",
                  "pack_cover_value": 353.81,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5",
                  "pack_cover_value": 437.58,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_11",
                  "pack_cover_value": 554.62,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_11",
                  "pack_cover_value": 638.39,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_10",
                  "pack_cover_value": 509.43,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_10_11",
                  "pack_cover_value": 710.24,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_8",
                  "pack_cover_value": 397.39,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "8"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_8",
                  "pack_cover_value": 481.16,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "8"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_8_11",
                  "pack_cover_value": 598.2,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "8", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_8_11",
                  "pack_cover_value": 681.97,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "8", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_8_10",
                  "pack_cover_value": 553.01,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "8", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_8_10_11",
                  "pack_cover_value": 753.82,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "8", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_7",
                  "pack_cover_value": 373.71,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "7"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7",
                  "pack_cover_value": 457.48,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_7_11",
                  "pack_cover_value": 574.52,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "7", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_11",
                  "pack_cover_value": 658.29,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_10",
                  "pack_cover_value": 529.33,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_10_11",
                  "pack_cover_value": 730.14,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_7_8",
                  "pack_cover_value": 417.29,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "7", "8"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_8",
                  "pack_cover_value": 501.06,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "8"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_7_8_11",
                  "pack_cover_value": 618.1,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "7", "8", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_8_11",
                  "pack_cover_value": 701.87,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "8", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_8_10",
                  "pack_cover_value": 572.91,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "8", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_8_10_11",
                  "pack_cover_value": 773.72,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "8", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_9",
                  "pack_cover_value": 372.81,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_9",
                  "pack_cover_value": 456.58,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_9_11",
                  "pack_cover_value": 573.62,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_9_11",
                  "pack_cover_value": 657.39,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_9_10",
                  "pack_cover_value": 528.43,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "9", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_9_10_11",
                  "pack_cover_value": 729.24,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "9", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_8_9",
                  "pack_cover_value": 416.39,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "8", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_8_9",
                  "pack_cover_value": 500.16,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "8", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_8_9_11",
                  "pack_cover_value": 617.2,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "8", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_8_9_11",
                  "pack_cover_value": 700.97,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "8", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_8_9_10",
                  "pack_cover_value": 572.01,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "8", "9", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_8_9_10_11",
                  "pack_cover_value": 772.82,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "8", "9", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_7_9",
                  "pack_cover_value": 392.71,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "7", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_9",
                  "pack_cover_value": 476.48,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_7_9_11",
                  "pack_cover_value": 593.52,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "7", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_9_11",
                  "pack_cover_value": 677.29,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_9_10",
                  "pack_cover_value": 548.33,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "9", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_9_10_11",
                  "pack_cover_value": 749.14,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "9", "10", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_7_8_9",
                  "pack_cover_value": 436.29,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "7", "8", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_8_9",
                  "pack_cover_value": 520.06,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "8", "9"]
                  }
                }, {
                  "pack_cover_id": "conte_1_5_7_8_9_11",
                  "pack_cover_value": 637.1,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "5", "7", "8", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_8_9_11",
                  "pack_cover_value": 720.87,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "8", "9", "11"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_8_9_10",
                  "pack_cover_value": 591.91,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "8", "9", "10"]
                  }
                }, {
                  "pack_cover_id": "conte_1_3_5_7_8_9_10_11",
                  "pack_cover_value": 792.72,
                  "pack_cover_list": {
                    "pack_cover_cover": [1, "3", "5", "7", "8", "9", "10", "11"]
                  }
                }]
              }
            }
          }, {
            "insurance_id": 440,
            "insurance_data": {
              "insurance_name": "Quixa",
              "insurance_teaser": "",
              "insurance_logo": "",
              "saving_allowed": 1,
              "autosaving": 0,
              "expiration": 0,
              "full_price": "764",
              "bundle_covers": {
                "bundle_cover": [1]
              },
              "enrichments": {
                "enrichment": []
              },
              "commission_abs": 16,
              "commission_rel": 2.09,
              "covers": {
                "cover": [{
                  "cover_id": 5,
                  "cover_value": "40"
                }, {
                  "cover_id": 7,
                  "cover_value": "19"
                }, {
                  "cover_id": 9,
                  "cover_value": "24"
                }]
              },
              "pack_covers": {
                "pack_cover": [{
                  "pack_cover_id": "quixa_RCA",
                  "pack_cover_value": "764",
                  "pack_cover_list": {
                    "pack_cover_cover": [1]
                  }
                }]
              }
            }
          }]
        }
      }
    }